# Generated by Django 4.2 on 2023-06-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
