# Generated by Django 4.2 on 2023-06-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonmanager', '0002_customer_profession_staffmember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='service_images/'),
        ),
    ]
