# Generated by Django 4.2.2 on 2023-07-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonmanager', '0004_packages_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='customer',
        ),
        migrations.AddField(
            model_name='packages',
            name='validity',
            field=models.CharField(choices=[('1M', '1 month'), ('6M', '6 months'), ('1Y', '1 year')], default='1M', max_length=2),
        ),
    ]
