# Generated by Django 4.2.2 on 2023-07-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salonmanager', '0005_remove_packages_customer_packages_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times the service can be used within the validity period')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonmanager.packages')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonmanager.service')),
            ],
        ),
    ]
