# Generated by Django 4.2 on 2023-07-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonmanager', '0008_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='validity',
            field=models.CharField(choices=[('1M', '1 month'), ('6M', '6 months'), ('1Y', '1 year')], max_length=2),
        ),
    ]
