# Generated by Django 4.2.2 on 2023-07-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salonmanager', '0012_appointment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='staff_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='salonmanager.staffmember'),
        ),
    ]
