# Generated by Django 4.2.2 on 2023-07-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salonmanager', '0013_invoice_customer_name_invoice_staff_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='salonmanager.appointment'),
        ),
    ]
