# Generated by Django 4.2.2 on 2023-07-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salonmanager', '0014_alter_invoice_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='appointment',
        ),
    ]
